version = 1
SPDX-PackageName = "44mesh"
SPDX-PackageSupplier = "AlterMundi"
SPDX-PackageDownloadLocation = "https://github.com/altermundi/44mesh"

[[annotations]]
path = "deploy/zerotier-ui/network-config-example.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 AlterMundi"
SPDX-License-Identifier = "GPL-3.0-only"
