# SPDX-FileCopyrightText: 2025 AlterMundi
#
# SPDX-License-Identifier: GPL-3.0-only

services:
  zerotier:
    build: .
    # image: zerotier/zerotier:1.14.2
    container_name: zerotier
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN  # required for tun/tap and network namespace management in Docker
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - zerotier_data:/var/lib/zerotier-one
      - ./local.conf:/var/lib/zerotier-one/local.conf:ro
      - ./network.local.conf:/tmp/network.local.conf:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
    environment:
      ZEROTIER_API_SECRET: "${ZEROTIER_API_SECRET}"
      ZEROTIER_IDENTITY_PUBLIC: "${ZEROTIER_IDENTITY_PUBLIC}"
      ZEROTIER_IDENTITY_SECRET: "${ZEROTIER_IDENTITY_SECRET}"
    entrypoint: /entrypoint.sh
    command: ["${ZT_NETWORK_ID}"]
    healthcheck:
      test: ["CMD-SHELL", "zerotier-cli listnetworks | grep -q OK"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 10s
    restart: unless-stopped

volumes:
  zerotier_data:
